### ISSUE TITLE
Is Qscintilla python only?

### ISSUE THREAD

**Issue by Ayymoose** [opencor/qscintilla#2]
Apologies for the basic question but can QScintilla be used with C++ instead of Python?

**Comment by agarny** [comment]
Please note that this is not the official repository of QScintilla, just a copy that we use in our [project](https://github.com/opencor/opencor). For the official version of QScintilla, please go to https://www.riverbankcomputing.com/software/qscintilla/.

Still, to answer your question: yes, QScintilla can be used with C++. This is what we do in our [project](https://github.com/opencor/opencor).
